version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25.4
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/certs:ro
    depends_on:
      - idp
    environment:
      TZ: "Asia/Tokyo"

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/keycloak-db:/var/lib/postgresql/data

  idp:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    depends_on:
      - keycloak-db
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./data/keycloak:/opt/keycloak/data
      - ./certs/server.crt:/etc/x509/https/tls.crt
      - ./certs/server.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_PROXY_HEADERS: "forwarded"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_LOG_LEVEL: DEBUG
      KC_HOSTNAME_STRICT: "false"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

    command:
      - start-dev
